# Generated by Django 5.0.3 on 2024-04-29 20:55

import uuid
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippetstests', '0011_nonautocompletesearchablesnippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatablesnippet',
            name='translation_key',
            field=wagtail.fields.Char32UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
