# Generated by Django 5.0.3 on 2024-04-29 20:55

import uuid
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0036_complexdefaultstreampage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='translation_key',
            field=wagtail.fields.Char32UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='eventpagecarouselitem',
            name='translation_key',
            field=wagtail.fields.Char32UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='eventpagerelatedlink',
            name='translation_key',
            field=wagtail.fields.Char32UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='eventpagespeaker',
            name='translation_key',
            field=wagtail.fields.Char32UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='eventpagespeakeraward',
            name='translation_key',
            field=wagtail.fields.Char32UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='fullfeaturedsnippet',
            name='translation_key',
            field=wagtail.fields.Char32UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
