# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0016_deprecate_rendition_filter_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendition',
            name='filter',
        ),

        # Set max_length of rendition.focal_point_key to 16, as the previous value of 255
        # (which existed on Wagtail <= 1.8) causes the unique_together index to overflow MySQL's
        # maximum length when the utf8mb4 char set is in use. This has been retrospectively
        # changed in earlier migrations (0001 and 0004) to allow migrations to run successfully
        # on that setup, so new databases created against Wagtail >= 1.9 will _already_ have a
        # max_length of 16 at this point; this AlterField operation only exists for the benefit
        # of databases being upgraded from Wagtail <= 1.8. For projects with a custom image model,
        # ./manage.py makemigrations will generate an AlterField operation matching this one.
        migrations.AlterField(
            model_name='rendition',
            name='focal_point_key',
            field=models.CharField(blank=True, default='', max_length=16, editable=False),
        ),
    ]
