# Generated by Django 5.0.3 on 2024-04-29 20:55

import uuid
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modellogentry',
            name='uuid',
            field=wagtail.fields.Char32UUIDField(blank=True, editable=False, help_text='Log entries that happened as part of the same user action are assigned the same UUID', null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='translation_key',
            field=wagtail.fields.Char32UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='pagelogentry',
            name='uuid',
            field=wagtail.fields.Char32UUIDField(blank=True, editable=False, help_text='Log entries that happened as part of the same user action are assigned the same UUID', null=True),
        ),
        migrations.AlterField(
            model_name='referenceindex',
            name='content_path_hash',
            field=wagtail.fields.Char32UUIDField(),
        ),
    ]
