# Generated by Django 1.9.1 on 2016-02-12 10:55
import django.db.models.deletion
from django.db import migrations, models

import wagtail.contrib.routable_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0024_alter_page_content_type_on_delete_behaviour"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutablePageTest",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="basepage.BasePage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "basepage.basepage",
            ),
        ),
    ]
