name: Wagtail CI

on:
  push:
  pull_request:

jobs:
  test-sqlite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: 3.7
            django: "Django>=3.0,<3.1"
          - python: 3.9
            django: "Django>=3.1,<3.2"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[testing]
          pip install ${{ matrix.django }}
      - name: Test
        run: |
          ./runtests.py
        env:
          DATABASE_ENGINE: django.db.backends.sqlite3

  test-postgres:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: 3.8
            django: "Django>=3.1,<3.2"
          - python: 3.9
            django: "Django>=3.1,<3.2"

    services:
      postgres:
        image: postgres:10.8
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[testing]
          pip install "psycopg2>=2.6"
          pip install ${{ matrix.django }}
      - name: Test
        run: |
          ./runtests.py
        env:
          DATABASE_ENGINE: django.db.backends.postgresql
          DATABASE_HOST: localhost
          DATABASE_USER: postgres
          DATABASE_PASS: postgres
