# Generated by Django 5.0.3 on 2024-04-29 20:55

import uuid
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('i18n', '0002_clusterabletestmodel_clusterabletestmodelchild_clusterabletestmodeltranslatablechild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterabletestmodel',
            name='translation_key',
            field=wagtail.fields.Char32UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='clusterabletestmodeltranslatablechild',
            name='translation_key',
            field=wagtail.fields.Char32UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='testchildobject',
            name='translation_key',
            field=wagtail.fields.Char32UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='translation_key',
            field=wagtail.fields.Char32UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='testnonparentalchildobject',
            name='translation_key',
            field=wagtail.fields.Char32UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
